import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Video record and upload",
  description: "Generated by Nafis Tarik",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
